# Generated by Django 4.1.7 on 2023-07-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ghgj', upload_to='pictures'),
            preserve_default=False,
        ),
    ]
